export class EventConstants {
  static readonly PAY_SUCCESS = 'paySuccess'
  static readonly LIMIT_CAMPAIGN = 'limitCampaign'
  static readonly LIMIT_GIFT = 'limitGift'
  static readonly OAID_READY = 'oaidReady'
  static readonly PPT_ADD_SUCCESS = 'pptAddSuccess'
  static readonly LOGIN_STATE_CHANGED = 'loginStateChanged'
  static readonly KEYBOARD_SHOW_HIDE = 'keyboardShowHide'
  static readonly VIP_INTERCEPT = 'vipIntercept'
}
